services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: AuthSQL
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: drs_users_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      timeout: 20s
      retries: 10
      interval: 5s

  # Python Flask Server 1 - Users & Auth
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5050:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://root:1234@db:3306/drs_users_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
    networks:
      - app-network
    restart: unless-stopped

  # Python Flask Server 2 - Flights
  flight_service:
    build:
      context: ./flight_service
      dockerfile: Dockerfile
    container_name: flight_service
    ports:
      - "5051:5000"   # ako i flight_service gunicorn slu≈°a na 5000 u kontejneru
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://root:1234@db:3306/drs_flights_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./flight_service:/app
    networks:
      - app-network
    restart: unless-stopped

  # React Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"
    environment:
      VITE_GATEWAY_URL: http://localhost:5050
      VITE_FLIGHTS_URL: http://localhost:5051
    depends_on:
      - server
      - flight_service
    volumes:
      - ./client/src:/app/src
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge